{"name": "Создание нового сотрудника.", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nTypeError: EmployeeClass.employee_post() takes 7 positional arguments but 9 were given", "trace": "@allure.description(\"Создать новую компанию, в этой компании создать запись о новом сотруднике. Сделать запрос о создании \\\n                        по  API и через БД. В запросе по API намерено отправить невалидные данные. \\\n                        Сравнить результаты возвращаемых ответов. Проверить статус-код, возвращаемый по API\")\n    @allure.feature(\"Негативная проверка\")\n    @allure.title(\"Создание нового сотрудника.\")\n    @allure.severity(\"Critical\")\n    @pytest.mark.xfail()\n    def test_invalid_create_new_note():\n        with allure.step(\"Сформировать невалидные значения для запроса\"):\n            company_id = driver.create_company(fake.name(), fake.text(20))\n            first_name = fake.first_name()\n            last_name = fake.last_name()\n            middle_name = fake.first_name()\n            phone = \"2222222222222\"\n            url = fake.url()\n            godzilla = fake.text(10)\n            date = fake.date_time()\n        with allure.step(\"Сделать запрос по API\"):\n>           driver.employee_post(company_id, first_name, last_name, middle_name, phone, url, godzilla, date)\nE           TypeError: EmployeeClass.employee_post() takes 7 positional arguments but 9 were given\n\ntest_employee_page_1.py:112: TypeError"}, "description": "Создать новую компанию, в этой компании создать запись о новом сотруднике. Сделать запрос о создании                     по  API и через БД. В запросе по API намерено отправить невалидные данные.                     Сравнить результаты возвращаемых ответов. Проверить статус-код, возвращаемый по API", "steps": [{"name": "Сформировать невалидные значения для запроса", "status": "passed", "start": 1678199351720, "stop": 1678199352175}, {"name": "Сделать запрос по API", "status": "broken", "statusDetails": {"message": "TypeError: EmployeeClass.employee_post() takes 7 positional arguments but 9 were given\n", "trace": "  File \"/Users/vadim/Documents/My_GIT_hub/SkyPro_Automation_Test/Lesson_10/test_employee_page_1.py\", line 112, in test_invalid_create_new_note\n    driver.employee_post(company_id, first_name, last_name, middle_name, phone, url, godzilla, date)\n"}, "start": 1678199352175, "stop": 1678199352175}], "start": 1678199351720, "stop": 1678199352177, "uuid": "4e7a3a57-63ad-44cc-9174-498a17d3245f", "historyId": "41828e90d9ef6dc134dd870bba47b6e8", "testCaseId": "70cc4936c32642437ef271b728956204", "fullName": "test_employee_page_1#test_invalid_create_new_note", "labels": [{"name": "feature", "value": "Негативная проверка"}, {"name": "severity", "value": "Critical"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_employee_page_1"}, {"name": "host", "value": "VAdims-Mac-mini.local"}, {"name": "thread", "value": "99325-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_employee_page_1"}]}