{"name": "Создание записи нового сотрудника. Позитивня проверка", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "@allure.id(\"Vadim kandeev. Test_3\")\n    @allure.story(\"Создание записи нового сотрудника\")\n    @allure.title(\"Создание записи нового сотрудника. Позитивня проверка\")\n    def test_valid_create_new_note():\n    \n        company_id = 1357\n        request_text = \"select first_name, last_name, middle_name, phone, avatar_url, \\\"isActive\\\", id from employee e where id = :curent_id \"\n        api_resp_first_name = \"Dart\"\n        api_resp_last_name = \"Waider\"\n        api_resp_middle_name = \"Sith\"\n        api_resp_phone = \"87776665544\"\n        api_resp_url = \"www.StarWars.com\"\n        api_resp_new_worker = driver.employee_post(company_id, api_resp_first_name, api_resp_last_name, api_resp_middle_name, api_resp_phone, api_resp_url)\n        api_resp_new_worker_id = api_resp_new_worker[0]['id'] # записываем новый id в переменную, чтобы создать запрос в БД\n>       with allure(\"Сделать запрос вновь созданной записи из БД\"):\nE       TypeError: 'module' object is not callable\n\ntest_employee_page_1.py:62: TypeError"}, "start": 1677871018373, "stop": 1677871019198, "uuid": "6d39f817-fe0c-4a8a-9a3c-cad04f69cb8b", "historyId": "c655cf5adf7eb7d6627cb940beabbf14", "testCaseId": "ab43fa5ed4bf622ceeaade7e9a6ab374", "fullName": "test_employee_page_1#test_valid_create_new_note", "labels": [{"name": "story", "value": "Создание записи нового сотрудника"}, {"name": "as_id", "value": "Vadim kandeev. Test_3"}, {"name": "suite", "value": "test_employee_page_1"}, {"name": "host", "value": "VAdims-Mac-mini.local"}, {"name": "thread", "value": "9139-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_employee_page_1"}]}